### ISSUE TITLE
Java-Go implementation discrepancies

### ISSUE THREAD

**Issue by NoamRabbani** [abcxyz/lumberjack#101]
We should make them consistent:

- [ ] In a config file, Java uses selector: `abcxyz.test.Talker/Hello`, Go uses selector `/abcxyz.test.Talker/Hello`. Go has a leading slash. In Go, interception won't work without the leading slash. Idk if Interceptor works in Java with the leading slash
- [x] Java accepts lists as JWT. Go should do the same (#73)
- [x] In Java, non-wildcard selector matches a method name if the select is a prefix of the method name. In Go, prefix is not enough, it has to be an exact match. [Java code location](https://github.com/abcxyz/lumberjack/blob/main/clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/config/Selector.java#L68) [Go code location](https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/audit/rules.go#L59)
- [x] Java handles nil values in the config file gracefully thanks the defaulting. Go has trouble with nil values. #64 should fix this when we migrate to koanf
- [x] Java doesn't support env vars in integration tests, Go does (#89)
- [x] Go validation processor requires a service name, but Java doesnt [java code](https://github.com/abcxyz/lumberjack/blob/main/clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/processor/ValidationProcessor.java#L30) [go code](https://github.com/abcxyz/lumberjack/blob/main/clients/go/pkg/audit/validation.go#L29)
- [ ] Java has [memoization when matching a selector to a method name](https://github.com/abcxyz/lumberjack/blob/6da72baada70ab54808bb9e759cf185a690bae12/clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/AuditLoggingServerInterceptor.java#L59). Go doesn't
